/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imageeditor4_ImageBlendingTask */

#ifndef _Included_com_example_imageeditor4_ImageBlendingTask
#define _Included_com_example_imageeditor4_ImageBlendingTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imageeditor4_ImageBlendingTask
 * Method:    poissonBlending
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_example_imageeditor4_ImageBlendingTask_poissonBlending
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
